name: "CI/CD {{ROUTE}} docker image"

on:
  push:
    branches: [ main ]
    paths:
      - "{{ROUTE}}/Dockerfile"
      - "{{ROUTE}}/environment.yml"
      - ".github/workflows/{{ROUTE}}-docker-image.yml"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  continuous-integration-docker-image-ecr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker image and push
        uses: docker/build-push-action@v2
        with:
          file: {{ROUTE}}/Dockerfile
          tags: {{ROUTE}}:latest
          build-args: ENV_YML={{ROUTE}}/environment.yml
          outputs: type=docker, dest=/tmp/dockerimage.tar

      - name: Load Docker image
        run: |
          docker load --input /tmp/dockerimage.tar
          docker image ls -a

      - name: Test scripts
        run: |
          mkdir data/output
          cd {{ROUTE}}
          make test_{{ROUTE}}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dockerimage
          path: /tmp/dockerimage.tar

      - name: Upload outputs
        uses: actions/upload-artifact@v2
        with:
          name: {{ROUTE}}-output
          path: data/output/

  continuous-deployment-docker-image-ecr:
    runs-on: ubuntu-latest
    needs: [continuous-integration-docker-image-ecr]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dockerimage
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/dockerimage.tar
          docker image ls -a

      - name: Push to ECR
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_DEFAULT_REGION }}
          image: {{ROUTE}}
